### ISSUE TITLE
Json polymorphism support

### ISSUE THREAD

**Issue by beku8** [boonproject/boon#279]
I would like to switch from Jackson parsing but one important feature seems to be missing.
Is there any way to do a mapping for ```abstract``` classes as Jackson does? e.g ```@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="@class")
public abstract class AbstractFoo{...}```

**Comment by RichardHightower** [comment]
status? I have tests showing abstract classes working. Can you rerpdouce the issue?

**Comment by RichardHightower** [comment]
Did you try it?

**Comment by beku8** [comment]
Yes I have, it works. Sorry for the late response, you may close the issue

**Comment by RichardHightower** [comment]
Thanks.

On Tue, Jan 20, 2015 at 5:13 PM, beku8 <notifications@github.com> wrote:

> Closed #279 <https://github.com/boonproject/boon/issues/279>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/279#event-222029865>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by Comandante** [comment]
How? I didn't find any support of polymorphism in boon.
Let's say, you have List<Itinerary> itineraries
and several different classes that extends Itinerary like AirItem/HotelItem/AutoItem etc.
How to unmarshal such kind of json based on some internal field?

**Comment by RichardHightower** [comment]
There is an option to output the classname as part of the JSON
serialization.
If you do this, then it will read that and use this classname to
instantiate the right class.

I believe if outputs to a field called class.
If class is present, it uses class to instantiate the object.


On Tue, Jul 7, 2015 at 6:33 AM, Vlad <notifications@github.com> wrote:

> How? I didn't find any support of polymorphism in boon.
> Let's say, you have List itineraries
> and several different classes that extends Itinerary like
> AirItem/HotelItem/AutoItem etc.
> How to unmarshal such kind of json based on some internal field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/279#issuecomment-119203499>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by Comandante** [comment]
ok, but what if class name changed after some package renaming i.e.?
Maybe there is some option to create some class synonim like JsonSubtype in Jackson?
Or use some base type enum field?

**Comment by RichardHightower** [comment]
Right. I know what you are talking about.
Boon does not have that as a feature.
You can parse to a Map of Maps and Lists, and then detect and map.

There is no way (other than doing it yourself) to map to a type based on an
enum.

It should be easy to write such a feature.

I have done things like this with Boon, but Boon does not expose it.

So I parse to map. Check a field, and then decide how to interprest a map
or sub map.



On Tue, Jul 7, 2015 at 9:48 AM, Vlad <notifications@github.com> wrote:

> ok, but what if class name changed after some package renaming i.e.?
> Maybe there is some option to create some class synonim like JsonSubtype
> in Jackson?
> Or use some base type enum field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/279#issuecomment-119265366>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
