### ISSUE TITLE
Gradle Wrapper Jar is Missing

### ISSUE THREAD

**Issue by JosephEarl** [boonproject/boon#283]
When executing a clean checkout any command with the gradle wrapper fails, e.g.

    $ ./gradlew clean
    Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

because the gradle wrapper jar is missing.

**Comment by RichardHightower** [comment]
I am learly about including binaries. Boon works with maven out of the gate. I guess folks will have to update this one themselves.
