### ISSUE TITLE
Boolean Wrapper has a string output instead of a boolean output

### ISSUE THREAD

**Issue by cmolocznik** [boonproject/boon#285]
{
    "abooleanfield": "true"
}

should be:

{
    "abooleanfield": true
}

Fixed it by putting this code below:

case BOOLEAN_WRAPPER:
                serializeFieldName(fieldName, builder);
                builder.add(value == Boolean.TRUE);
                return true;

in FieldSerializerUseAnnotationsImpl.java and FieldSerializerImpl.java

**Comment by RichardHightower** [comment]
the best kind of bug report... one with a solution. :) I will write a test and verify and then patch. Thanks.

**Comment by RichardHightower** [comment]
I was not able to reproduce this. Sample code?

**Comment by RichardHightower** [comment]
confirmed

**Comment by RichardHightower** [comment]
Fixed
