### ISSUE TITLE
Boon toJson not working in GAE environment

### ISSUE THREAD

**Issue by kerbymart** [boonproject/boon#286]
[INFO] Caused by: java.lang.ExceptionInInitializerError
[INFO] 	at org.boon.Str.underBarCase(Str.java:538)
[INFO] 	at org.boon.core.Sys.sysProp(Sys.java:334)
[INFO] 	at org.boon.core.timer.TimeKeeperBasic.<init>(TimeKeeperBasic.java:52)
[INFO] 	at org.boon.core.Sys.<clinit>(Sys.java:175)
[INFO] 	at org.boon.Boon.<clinit>(Boon.java:81)
[INFO] 	at com.myapp.resource.SystemInfoResource.represent(SystemInfoResource.java:28)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] 	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:115)
[INFO] 	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
[INFO] 	... 74 more
[INFO] Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
[INFO] 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
[INFO] 	at java.security.AccessController.checkPermission(AccessController.java:559)
[INFO] 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
[INFO] 	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:431)
[INFO] 	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1525)
[INFO] 	at java.lang.ClassLoader$1.run(ClassLoader.java:503)
[INFO] 	at java.lang.ClassLoader$1.run(ClassLoader.java:501)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:501)
[INFO] 	at org.boon.core.reflection.FastStringUtils.loadUnsafe(FastStringUtils.java:55)
[INFO] 	at org.boon.core.reflection.FastStringUtils.<clinit>(FastStringUtils.java:67)
[INFO] 	... 86 more
[INFO] 
[INFO] Dec 31, 2014 9:38:57 PM org.restlet.engine.log.LogFilter afterHandle

**Comment by kerbymart** [comment]
@RichardHightower will there be a fix for this?

**Comment by RichardHightower** [comment]
I suspect not. I don't think it will work in a GAE environment.


On Thu, Jan 1, 2015 at 2:15 AM, @kerbymart <notifications@github.com> wrote:

> @RichardHightower <https://github.com/RichardHightower> will there be a
> fix for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/286#issuecomment-68483689>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by kerbymart** [comment]
@RichardHightower what is the root cause anyway?

**Comment by revelfire** [comment]
Best guess without seeing the source code is something in your original:  [INFO] at com.myapp.resource.SystemInfoResource.represent(SystemInfoResource.java:28)  is trying to reflect on something that isn't allowed. The GAE runtime limits what is accessible via reflection.  

https://cloud.google.com/appengine/docs/java/#Java_The_sandbox

Read the headings: java.lang.System, Reflection

**Comment by kerbymart** [comment]
@revelfire Yes it is, however I think there is a way to make boon 100% compatible with GAE, @RichardHightower  what do you think? I will try to fork it and see what I can do.
