### ISSUE TITLE
org.boon.core.value.ValueContainer's inconsistent behavior

### ISSUE THREAD

**Issue by jakub-dzon** [boonproject/boon#289]
I'd like to use Boon JSON Parser to process "sparse" JSON documents (a lot of the fields are optional) and in case of `Integer` fields the `ValueContainer.intValue()` throws Exceptions while encountering `null` values. It is inconsistent with the behavior of other `*Value` methods (except for `longValue`). Is there a reason for such a behaviour? Of course, if I use `BigInteger` in place of `Integer` it works correctly, but I would prefer using `Integer' type. Is there other workaround?

**Comment by RichardHightower** [comment]
Just send a simple sample that reproduces the issue and I will fix it.

**Comment by RichardHightower** [comment]
Please send a simple example that reproduces this and I will fix it. This sounds like an important bug, and I would like to prioritize it higher, but I can't really do that without an example.

**Comment by jakub-dzon** [comment]
I'm sorry for replying so late. The code demonstrating the issue is in https://github.com/jakub-dzon/boon-integer.

**Comment by RichardHightower** [comment]
```java
package org.boon.bugs;

import org.boon.json.JsonParserAndMapper;
import org.boon.json.JsonParserFactory;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.nullValue;
import static org.junit.Assert.assertThat;

/**
 * Created by rhightower on 3/23/15.
 */
public class Bug289 {


    public static class Entity {
        String name;
        Integer someNumber;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Integer getSomeNumber() {
            return someNumber;
        }

        public void setSomeNumber(int someNumber) {
            this.someNumber = someNumber;
        }
    }

    @Test
    public void shouldParseNullInteger() {
        //Given
        JsonParserFactory jsonParserFactory = new JsonParserFactory();
        JsonParserAndMapper parserAndMapper = jsonParserFactory.create();


        //When
        Entity entity = parserAndMapper.parse(Entity.class, "{\n" +
                "  \"name\": \"A name\",\n" +
                "  \"someNumber\": null\n" +
                "}");


        //Then
        assertThat(entity.getName(), is("A name"));

        final Integer someNumber = entity.getSomeNumber();
        assertThat(someNumber, is(nullValue()));



        //When again
        entity = parserAndMapper.parse(Entity.class, "{\n" +
                "  \"name\": \"A name\",\n" +
                "  \"someNumber\": 1\n" +
                "}");


        //Then
        assertThat(entity.getName(), is("A name"));

        final int a = entity.getSomeNumber();
        assertThat(a, is(1));
    }
}

```

The issue as the value was null and you were trying to assign it to a primitive int.
It did not seem to have anything to do with Boon.

I fixed the issue by not assigning the value to an int.

Check you getter method in the example that you sent. 

The getter returned a primitive int.
Boon read the object correctly.

The value was null.

Thus someNumber was null.

But then when you call getSomeNumber... BOOM!

**Comment by jakub-dzon** [comment]
Thanks, the issue is gone in versions 0.12+. Good catch with the getter.

**Comment by RichardHightower** [comment]
Glad it is fixed. Thanks for reporting it and thanks for your detailed
error report.

On Tue, Mar 24, 2015 at 12:47 AM, Jakub Dżon <notifications@github.com>
wrote:

> Thanks, the issue is gone in versions 0.12+. Good catch with the getter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/289#issuecomment-85381828>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
