### ISSUE TITLE
issue w/ deleteDirRecursively

### ISSUE THREAD

**Issue by woki** [boonproject/boon#305]
Hey guys! Are you aware deleteDirRecursively is not working at all?

**Comment by RichardHightower** [comment]
I am not aware of that. Thanks for filing an issue.
We accept patches too. :)


On Tue, Mar 17, 2015 at 7:26 AM, Willian Oki <notifications@github.com>
wrote:

> Hey guys! Are you aware deleteDirRecursively is not working at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/305>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by woki** [comment]
trying to fix it right now. let you know when ok so you can use it for the
nexte release :)

On Tue, Mar 17, 2015 at 1:46 PM, Richard Hightower <notifications@github.com

**Comment by woki** [comment]
hey guys! here it goes:

org.boon.etcd.Request, line 188:

< if (this.method.equals("GET")) {
> if (this.method.equals("GET") || this.method.equals("DELETE")) {

Though the spec is not clear about entities (at least to me), DELETE is usually the same as GET under invocation perspective. Apart from that discussion, deleteDirRecursively() works fine this way.

Thx

**Comment by woki** [comment]
do you think it's going to 0.33? i'd appreciate since we're depending on etcd-client.

thx

**Comment by RichardHightower** [comment]
Ok

On Tuesday, March 17, 2015, Willian Oki <notifications@github.com> wrote:

> trying to fix it right now. let you know when ok so you can use it for the
> nexte release :)
>
> On Tue, Mar 17, 2015 at 1:46 PM, Richard Hightower <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > wrote:
>
> > I am not aware of that. Thanks for filing an issue.
> > We accept patches too. :)
> >
> >
> > On Tue, Mar 17, 2015 at 7:26 AM, Willian Oki <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Hey guys! Are you aware deleteDirRecursively is not working at all?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/boonproject/boon/issues/305>.
> > >
> >
> >
> >
> > --
> > *Rick Hightower*
> > (415) 968-9037
> > Profile <http://www.google.com/profiles/RichardHightower>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/boonproject/boon/issues/305#issuecomment-82469423>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/305#issuecomment-82482869>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
I merged your patch. I am closing this for now.
