### ISSUE TITLE
etcd-client Node not mapping dir attribute

### ISSUE THREAD

**Issue by woki** [boonproject/boon#307]
Though etcd response marks every node being a dir or not (dir, true/false) that's not mapped in org.boon.etcd.Node.

**Comment by RichardHightower** [comment]
I merged in the changes. @slandelle does the builds and publishes to the public repo.

BTW I thought we were going to use etcd on a project, but we ended up using consul which is a similar thing. I like them both.

I integrated consul into qbit, and am using it for some early service discovery and clustering for qbit. 

https://github.com/advantageous/qbit/tree/master/consul-client

I am considering using etcd as a provider as well. 

I like that both etcd and consul are microservices and they allow me to do service discovery in a consistent way that is compatible with non-Java stuff via JSON/HTTP.

What are you doing with etcd?

**Comment by woki** [comment]
Hi Richard/All

thanks, nice to know about consul (an also qbit, awesome)! We're building
up a kind of docker registry here and relying on etcd for that. The project
is at initial steps yet so there's room for technology changes, I guess.

Lets keep in touch! Regards
-Willian Oki

On Wed, Mar 18, 2015 at 6:21 PM, Richard Hightower <notifications@github.com

**Comment by RichardHightower** [comment]
Thanks for writing.
If you are just starting out, you should check out consul.io for sure.

On Thu, Mar 19, 2015 at 6:38 AM, Willian Oki <notifications@github.com>
wrote:

> Hi Richard/All
>
> thanks, nice to know about consul (an also qbit, awesome)! We're building
> up a kind of docker registry here and relying on etcd for that. The project
> is at initial steps yet so there's room for technology changes, I guess.
>
> Lets keep in touch! Regards
> -Willian Oki
>
> On Wed, Mar 18, 2015 at 6:21 PM, Richard Hightower <
> notifications@github.com
> > wrote:
>
> > I merged in the changes. @slandelle <https://github.com/slandelle> does
> > the builds and publishes to the public repo.
> >
> > BTW I thought we were going to use etcd on a project, but we ended up
> > using consul which is a similar thing. I like them both.
> >
> > I integrated consul into qbit, and am using it for some early service
> > discovery and clustering for qbit.
> >
> > https://github.com/advantageous/qbit/tree/master/consul-client
> >
> > I am considering using etcd as a provider as well.
> >
> > I like that both etcd and consul are microservices and they allow me to
> do
> > service discovery in a consistent way that is compatible with non-Java
> > stuff via JSON/HTTP.
> >
> > What are you doing with etcd?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/boonproject/boon/issues/307#issuecomment-83183851>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/307#issuecomment-83581237>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
