### ISSUE TITLE
Malformed JSON of Arrays with empty elements

### ISSUE THREAD

**Issue by atheedom** [boonproject/boon#309]
When parsing a String array with empty elements the resulting JSON includes trailing commas for each empty element. 

String[] cats = new String[10];
cats[0] = "Felix";

will serialise to ["Felix",,,,,,,,,]

this is malformed and should not contain these trailing commas

**Comment by RichardHightower** [comment]
you are right. I will ignore nulls in array I guess.

Any thoughts on how to handle a sparsely populate array?

On Thu, Mar 19, 2015 at 9:04 AM, Alex Theedom <notifications@github.com>
wrote:

> When parsing a String array with empty elements the resulting JSON
> includes trailing commas for each empty element.
>
> String[] cats = new String[10];
> cats[0] = "Felix";
>
> will serialise to ["Felix",,,,,,,,,]
>
> this is malformed and should not contain these trailing commas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/309>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by atheedom** [comment]
I thought of doing the same. I forked the code this afternoon and starting working on a solution. Looks as simple as just ignoring nulls. I will write some tests and if all pass do a pull request.

**Comment by RichardHightower** [comment]
Sounds good. Thanks.

On Thursday, March 19, 2015, Alex Theedom <notifications@github.com> wrote:

> I thought of doing the same. I forked the code this afternoon and starting
> working on a solution. Looks as simple as just ignoring nulls. I will write
> some tests and if all pass do a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/309#issuecomment-83788278>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by atheedom** [comment]
The only issue I found with this approach is that array position is not preserved.

String[] cats = new String[10];
cats[0] = "Felix";
cats[5] = "Tom";

will serialise to ["Felix","Tom"], while it should be something like ["Felix","","","","","Tom","","","","",""]

Although valid JSON it does not represent the original Array form which ideally it should be. 

I'll look into it further.

**Comment by RichardHightower** [comment]
I think we should null fill it instead of empty strings to preserve order.

like ["Felix", null, null, null, null,"Tom", null, ...

On Friday, March 20, 2015, Alex Theedom <notifications@github.com> wrote:

> The only issue I found with this approach is that array position is not
> preserved.
>
> String[] cats = new String[10];
> cats[0] = "Felix";
> cats[5] = "Tom";
>
> will serialise to ["Felix","Tom"], while it should be something like
> ["Felix","","","","","Tom","","","","",""]
>
> Although valid JSON it does not represent the original Array form which
> ideally it should be.
>
> I'll look into it further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/309#issuecomment-83977753>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
Thank you for working on this.
