### ISSUE TITLE
Cannot parse double field such as {"doubleValue":"NaN"}

### ISSUE THREAD

**Issue by michael-g** [boonproject/boon#311]
Exception is raised from line 1131 in `CharScanner.java` in method `parseDouble(char[],int,int)`.

**Comment by RichardHightower** [comment]
Ok.. that sounds like an easy fix. Thanks.

On Thu, Apr 16, 2015 at 1:35 PM, Michael <notifications@github.com> wrote:

> Exception is raised from line 1131 in CharScanner.java in method
> parseDouble(char[],int,int).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/311>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by michael-g** [comment]
Sweet! Sorry for the cursory bug report (no test case, etc), but I'm in
trouble with the missus for spending too much time with my computer. Good
fag-packet results vs Gson, btw, on large message sizes. Timed at c. 9
seconds vs 13 seconds for 1000 runs over roughly 30 separate messages. Nice
one!

**Comment by RichardHightower** [comment]
https://answers.yahoo.com/question/index?qid=20080107070851AAqiHyu

I had to look that one up...

The literal translation is "back of a cigarette packet".

We don't say fag in the US. It means something else.

We say the same thing but its on a match book cover. :)

But same idea... :)

Lost in translation no more.

On Thu, Apr 16, 2015 at 3:28 PM, Michael <notifications@github.com> wrote:

> Sweet! Sorry for the cursory bug report (no test case, etc), but I'm in
> trouble with the missus for spending too much time with my computer. Good
> fag-packet results vs Gson, btw, on large message sizes. Timed at c. 9
> seconds vs 13 seconds for 1000 runs over roughly 30 separate messages. Nice
> one!
> On 16 Apr 2015 23:22, "Richard Hightower" <notifications@github.com>
> wrote:
>
> > Ok.. that sounds like an easy fix. Thanks.
> >
> > On Thu, Apr 16, 2015 at 1:35 PM, Michael <notifications@github.com>
> wrote:
> >
> > > Exception is raised from line 1131 in CharScanner.java in method
> > > parseDouble(char[],int,int).
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/boonproject/boon/issues/311>.
> > >
> >
> >
> >
> > --
> > *Rick Hightower*
> > (415) 968-9037
> > Profile <http://www.google.com/profiles/RichardHightower>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/boonproject/boon/issues/311#issuecomment-93852620>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/311#issuecomment-93853600>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by michael-g** [comment]
LOL. Yep, that comment is giving quite a bit away in terms of clarity! Must be what happens when you try to type something on a smartphone...

**Comment by RichardHightower** [comment]
Ok.. looking into this now.

**Comment by RichardHightower** [comment]
Fixed.

**Comment by michael-g** [comment]
Brilliant. Will test drive soon. Thanks!
