### ISSUE TITLE
Sys crash on "1.7.0_09-icedtea" java version

### ISSUE THREAD

**Issue by slandelle** [boonproject/boon#315]
This is the build name pattern for OpenJDK on Fedora, Gentoo and Debian.

I will provide a pull request.

**Comment by RichardHightower** [comment]
ok.. thanks.

**Comment by slandelle** [comment]
@RichardHightower Hey! I was lazy and directly fix, as it was dead simple. I hope you don't mind.

Can I release?

**Comment by RichardHightower** [comment]
yes you can.

**Comment by slandelle** [comment]
Done, thanks!

**Comment by slandelle** [comment]
@RichardHightower Do you want me to port this to https://github.com/advantageous/boon?

**Comment by RichardHightower** [comment]
That would be awesome. :)

On Thu, May 14, 2015 at 12:57 PM, Stephane Landelle <
notifications@github.com> wrote:

> @RichardHightower <https://github.com/RichardHightower> Do you want me to
> port this to https://github.com/advantageous/boon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boonproject/boon/issues/315#issuecomment-102150631>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by slandelle** [comment]
Done: https://github.com/advantageous/boon/pull/1
