### ISSUE TITLE
In ObjectFilter.endsWith uses StartsWith instead of EndsWith

### ISSUE THREAD

**Issue by mouette** [boonproject/boon#336]
I think there is an issue withe the criterion endsWith.

At line 335 of ObjectFilter
                return fieldValue.toString().startsWith(value.toString());
instead of
                return fieldValue.toString().endsWith(value.toString());

Thanks

**Comment by RichardHightower** [comment]
thanks

**Comment by RichardHightower** [comment]
I will fix it.
