### ISSUE TITLE
Boon Long conversion fails for larger numbers 

### ISSUE THREAD

**Issue by SagarN** [boonproject/boon#354]
Some Numbers whose string length is equal to that of Long.Max  
in this case it will fail at digit[1]. The digit[1] is greater than 2 (Long.Max[1])
``` 
@Test
    public void testBoonConversion () {
        final String aLongNumberAsString = "1520698688883654656";
        final long aLongNumberAsLong = Long.valueOf(aLongNumberAsString);

        Assert.assertTrue("Number is less than long max ", aLongNumberAsLong < Long.MAX_VALUE);
        Assert.assertEquals(" Numbers should match after conversion", aLongNumberAsString, String.valueOf(aLongNumberAsLong));
        Assert.assertTrue("Should be valid a long ", CharScanner.isLong(aLongNumberAsString.toCharArray(), 0, aLongNumberAsString.length()));

    }
```

**Comment by slandelle** [comment]
I've provided a PR against "advantageous/boon" with the fix. It should be easy to port, code seemed identical to me there.

**Comment by RichardHightower** [comment]
https://github.com/advantageous/boon/pull/19

**Comment by RichardHightower** [comment]
Sagar... you are using Advantageous Boon BTW since you are using QBit.

**Comment by SagarN** [comment]
Not sure what it means. 
Please clarify 

- Sagar

**Comment by RichardHightower** [comment]
Stephane Landele fixed the qbit boon version. I will do a release with that fix.
