### ISSUE TITLE
boon saves empty attributes

### ISSUE THREAD

**Issue by javamonkey79** [boonproject/boon#355]
Consider this case:

`
public class Cat {
public String name;
public String type;
public String sex;
//... constructor, etc omitted for brevity
}
Cat mittens = new Cat("mittens", "calico", "");
`

In this case, Boon.toJson(mittens) will give us:

`
{
"name":"mittens",
"type":"calico",
"sex":""
}
`

Is there any way to ignore empty values? If not, will you consider a patch to allow for this?

**Comment by javamonkey79** [comment]
Digging deeper, I would have expected this to work but did not:

`JsonSerializer jsonSerializer = new JsonSerializerFactory().setIncludeEmpty(false).create();`
 `System.out.println(jsonSerializer.serialize(mittens));`

**Comment by javamonkey79** [comment]
Ok, I see now that the includeEmpty property pertains to collections. I also see that StringSerializerImpl is where blank String checking would occur. However, it appears there is no way to inject in subclasses in to the factory? I think if you refactored the create method to read from protected methods, this would not be an issue: users could then subclass the factory and provide a version that suits their needs.

**Comment by javamonkey79** [comment]
I've completed a simple version and issued a pull request:
https://github.com/boonproject/boon/pull/356

**Comment by javamonkey79** [comment]
I'm curious, is there something else I need to do here to get this rolled in?

**Comment by RichardHightower** [comment]
Let me look at your pull request. Been busy is all. :)

**Comment by RichardHightower** [comment]
I merged your request. It will get released the next time @slandelle does a release. If I remember correctly, I am not setup to do a release.

**Comment by javamonkey79** [comment]
Cool, thanks for merging it in @RichardHightower . @slandelle do you have an ETA on a release?

**Comment by slandelle** [comment]
Done :)

@RichardHightower Are there some patches here that needs to be ported on https://github.com/advantageous/boon?

**Comment by javamonkey79** [comment]
@RichardHightower wdyt about this type of behavior as default?

**Comment by RichardHightower** [comment]
Probably should be.

**Comment by javamonkey79** [comment]
Ok, I'll submit a pull later then.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by javamonkey79** [comment]
Ok, I've pushed my changes and submitted a pull request @RichardHightower

**Comment by RichardHightower** [comment]
looking now
